workflows:
  ios-workflow:
    name: RatoNet iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "RatoNet.xcodeproj"
        XCODE_SCHEME: "RatoNet"
        BUNDLE_ID: "com.eerimoq.Mobs"
        # Desabilitar plugins de pacotes para evitar erro de validação do PrepareLicenseList
        SWIFT_PACKAGE_PLUGIN_DISABLE: "1"
        XCODE_SKIP_PACKAGE_PLUGIN_VALIDATION: "1"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          # Instalar SwiftLint e SwiftFormat se necessário
          brew install swiftlint swiftformat || true
      - name: Resolve Swift packages
        script: |
          # Desabilitar plugins de pacotes para evitar erro de validação
          export SWIFT_PACKAGE_PLUGIN_DISABLE=1
          xcodebuild -resolvePackageDependencies -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -skipPackagePluginValidation
      - name: Fix Watch app product name and remove plugin dependency
        script: |
          # Modificar temporariamente o project.pbxproj para:
          # 1. Corrigir PRODUCT_NAME do RatoNetWatch
          # 2. Remover dependência do plugin PrepareLicenseList que está causando erro de validação
          python3 << 'EOF'
          import re
          
          project_file = "RatoNet.xcodeproj/project.pbxproj"
          
          with open(project_file, 'r', encoding='utf-8') as f:
              content = f.read()
          
          original_content = content
          changes_made = []
          
          # 1. Substituir PRODUCT_NAME = RatoNet; que está antes de SDKROOT = watchos;
          pattern1 = r'(PRODUCT_NAME = RatoNet;\s+SDKROOT = watchos;)'
          replacement1 = r'PRODUCT_NAME = RatoNetWatchApp;\n\t\t\t\tSDKROOT = watchos;'
          
          if re.search(pattern1, content):
              content = re.sub(pattern1, replacement1, content)
              changes_made.append("PRODUCT_NAME do RatoNetWatch modificado")
          else:
              pattern1_alt = r'(PRODUCT_NAME = RatoNet;[\s\n]+SDKROOT = watchos;)'
              if re.search(pattern1_alt, content):
                  content = re.sub(pattern1_alt, replacement1, content)
                  changes_made.append("PRODUCT_NAME do RatoNetWatch modificado")
          
          # 2. Remover o bloco completo do PBXTargetDependency que referencia PrepareLicenseList
          # Formato exato: IDENTIFIER /* PBXTargetDependency */ = { isa = PBXTargetDependency; productRef = IDENTIFIER /* PrepareLicenseList */; };
          pattern2 = r'\t\t\t[0-9A-F]+ /\* PBXTargetDependency \*/ = \{\s*isa = PBXTargetDependency;\s*productRef = [0-9A-F]+ /\* PrepareLicenseList \*/;\s*\};?\n'
          if re.search(pattern2, content):
              content = re.sub(pattern2, '', content)
              changes_made.append("Dependência do plugin PrepareLicenseList removida")
          
          # 3. Remover a definição do produto do plugin
          pattern3 = r'\t\t\t[0-9A-F]+ /\* PrepareLicenseList \*/ = \{\s*isa = XCSwiftPackageProductDependency;\s*package = [0-9A-F]+ /\* XCRemoteSwiftPackageReference "LicenseList" \*/;\s*productName = "plugin:PrepareLicenseList";\s*\};?\n'
          if re.search(pattern3, content):
              content = re.sub(pattern3, '', content)
              changes_made.append("Definição do produto PrepareLicenseList removida")
          
          if content != original_content:
              with open(project_file, 'w', encoding='utf-8') as f:
                  f.write(content)
              print("✅ Modificações aplicadas:")
              for change in changes_made:
                  print(f"   - {change}")
          else:
              print("⚠️  Nenhuma modificação necessária (pode já estar aplicada)")
          EOF
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          # Solução: Fazer archive do scheme principal
          # Limpar derived data para evitar problemas de cache de módulos
          mkdir -p build
          rm -rf build/DerivedData || true
          
          # Desabilitar plugins de pacotes para evitar erro de validação do PrepareLicenseList
          export SWIFT_PACKAGE_PLUGIN_DISABLE=1
          
          # Baixar componentes necessários do Xcode
          echo "📥 Baixando Metal Toolchain..."
          xcodebuild -downloadComponent MetalToolchain || true
          
          echo "📥 Baixando plataforma iOS..."
          xcodebuild -downloadPlatform iOS || true
          
          # Remover temporariamente a dependência do Watch app antes do archive
          # O Watch app é watchOS e não pode ser arquivado junto com iOS
          python3 << 'EOF'
          import re
          
          project_file = "RatoNet.xcodeproj/project.pbxproj"
          
          with open(project_file, 'r', encoding='utf-8') as f:
              content = f.read()
          
          # Fazer backup
          with open(project_file + '.backup', 'w', encoding='utf-8') as f:
              f.write(content)
          
          # Remover "Embed Watch Content" do buildPhases do target RatoNet
          # Procurar por: 03ECDF572B8E4E6000BD920E /* Embed Watch Content */,
          pattern1 = r'\t\t\t\t03ECDF572B8E4E6000BD920E /\* Embed Watch Content \*/,\n'
          content = re.sub(pattern1, '', content)
          
          # Remover a dependência do Watch app (PBXTargetDependency)
          # Procurar por: 03ECDF522B8E4E6000BD920E /* PBXTargetDependency */,
          pattern2 = r'\t\t\t\t03ECDF522B8E4E6000BD920E /\* PBXTargetDependency \*/,\n'
          content = re.sub(pattern2, '', content)
          
          with open(project_file, 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("✅ Dependência do Watch app removida temporariamente para o archive")
          EOF
          
          # Primeiro, fazer build completo do scheme para garantir que todas as dependências
          # sejam construídas na ordem correta (SDWebImage antes de SDWebImageWebPCoder)
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            -skipPackagePluginValidation \
            SKIP_INSTALL=YES \
            build || true
          
          # Agora fazer o archive usando -scheme (obrigatório quando usa -archivePath)
          echo "📦 Criando archive..."
          set +e  # Não sair imediatamente em caso de erro
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/RatoNet.xcarchive \
            -derivedDataPath build/DerivedData \
            -skipPackagePluginValidation \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            archive 2>&1 | tee build/archive.log
          ARCHIVE_EXIT_CODE=$?
          set -e
          
          # Verificar se o archive foi criado
          if [ -d "build/RatoNet.xcarchive" ]; then
              echo "✅ Archive criado com sucesso em build/RatoNet.xcarchive"
          else
              echo "❌ Archive não foi criado"
              echo "📋 Últimas linhas do log de archive:"
              tail -50 build/archive.log || true
              # Restaurar o backup antes de sair
              if [ -f "RatoNet.xcodeproj/project.pbxproj.backup" ]; then
                  mv "RatoNet.xcodeproj/project.pbxproj.backup" "RatoNet.xcodeproj/project.pbxproj"
              fi
              exit 1
          fi
          
          # Se o comando falhou mas o archive existe, continuar
          if [ $ARCHIVE_EXIT_CODE -ne 0 ]; then
              echo "⚠️  Comando de archive retornou código $ARCHIVE_EXIT_CODE, mas archive existe. Continuando..."
          fi
          
          # Restaurar o backup do project.pbxproj
          if [ -f "RatoNet.xcodeproj/project.pbxproj.backup" ]; then
              mv "RatoNet.xcodeproj/project.pbxproj.backup" "RatoNet.xcodeproj/project.pbxproj"
              echo "✅ Dependência do Watch app restaurada"
          fi
      - name: Export IPA
        script: |
          # Verificar se o archive existe antes de exportar
          if [ ! -d "build/RatoNet.xcarchive" ]; then
              echo "❌ Archive não encontrado em build/RatoNet.xcarchive"
              echo "📂 Procurando archives em outros locais..."
              find . -name "*.xcarchive" -type d 2>/dev/null | head -5
              exit 1
          fi
          
          echo "📦 Extraindo IPA do archive..."
          echo "📂 Estrutura do archive:"
          find build/RatoNet.xcarchive -type d -maxdepth 3 | head -20
          
          mkdir -p build/ipa
          
          # Procurar o .app em diferentes locais possíveis
          APP_PATH=""
          
          # Tentar diferentes caminhos
          if [ -d "build/RatoNet.xcarchive/Products/Applications" ]; then
              APP_PATH=$(find build/RatoNet.xcarchive/Products/Applications -name "*.app" -type d | head -1)
          fi
          
          if [ -z "$APP_PATH" ] && [ -d "build/RatoNet.xcarchive/Products" ]; then
              APP_PATH=$(find build/RatoNet.xcarchive/Products -name "*.app" -type d | head -1)
          fi
          
          if [ -z "$APP_PATH" ]; then
              APP_PATH=$(find build/RatoNet.xcarchive -name "*.app" -type d | head -1)
          fi
          
          if [ -z "$APP_PATH" ]; then
              echo "❌ Não foi possível encontrar o .app no archive"
              echo "📂 Conteúdo do archive:"
              ls -la build/RatoNet.xcarchive/
              if [ -d "build/RatoNet.xcarchive/Products" ]; then
                  echo "📂 Conteúdo de Products:"
                  ls -la build/RatoNet.xcarchive/Products/
              fi
              exit 1
          fi
          
          echo "📱 App encontrado: $APP_PATH"
          
          # Criar o Payload directory
          PAYLOAD_DIR="build/ipa/Payload"
          mkdir -p "$PAYLOAD_DIR"
          
          # Copiar o .app para Payload
          cp -R "$APP_PATH" "$PAYLOAD_DIR/"
          
          # Criar o IPA
          IPA_NAME="RatoNet.ipa"
          cd build/ipa
          zip -r "$IPA_NAME" Payload
          cd ../..
          
          # Verificar se o IPA foi criado
          if [ ! -f "build/ipa/$IPA_NAME" ]; then
              echo "❌ IPA não foi criado"
              exit 1
          fi
          
          echo "✅ IPA criado com sucesso: build/ipa/$IPA_NAME"
          ls -lh build/ipa/*.ipa
    artifacts:
      - build/ipa/*.ipa
      - build/*.dSYM.zip
    publishing:
      email:
        recipients:
          - user@example.com # Substitua pelo seu email
        notify:
          success: true
          failure: false
      # Descomente se quiser publicar no App Store Connect
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: false
      #   beta_groups:
      #     - group name 1
      #     - group name 2

